[target.aarch64-linux-android]
linker = "aarch64-linux-android33-clang"
ar = "llvm-ar"
rustflags = [
    "-C", "link-arg=-fuse-ld=lld",
    "-C", "link-arg=-z", "-C", "link-arg=max-page-size=16384"
]

[target.aarch64-unknown-linux-musl]
linker = "clang"
rustflags = [
    "-C", "link-arg=--target=aarch64-unknown-linux-musl",
    "-C", "link-arg=-fuse-ld=lld",
    "-C", "target-feature=+crt-static"
]
